Use UTF8 in LC_ALL.
rpm-software-management/rpmlint pull request #504
Opened 2020-11-02 16:19 UTC by marxin

It is needed in order to get proper encoded utf8 errors
for e.g. desktop-file-validate.

2020-11-02 16:24 UTC, Conan-Kudo requested changes

2020-11-02 16:24 UTC, Conan-Kudo commented on rpmlint/helpers.py
> +ENGLISH_ENVIROMENT = dict(os.environ, LC_ALL='en_US.utf8')
Isn't this `en_US.UTF-8`?

2020-11-02 16:28 UTC, marxin commented on rpmlint/helpers.py
> +ENGLISH_ENVIROMENT = dict(os.environ, LC_ALL='en_US.utf8')
Yes.

2020-11-02 18:16 UTC, scarabeusiv commented
Does there need to be else block after the try?

I don't think so...

2020-11-02 19:38 UTC, marxin commented
> Does there need to be else block after the try?

You are right!

2020-11-03 08:23 UTC, scarabeusiv commented
Now just one more, should there also be added toml description for the error?

2020-11-03 08:24 UTC, marxin commented
> Now just one more, should there also be added toml description for the error?

The error already exists:
```
non-utf8-desktopfile="""
The .desktop file is not encoded in UTF-8.
"""
```

2020-11-03 08:27 UTC, scarabeusiv commented
Aha!

2020-11-03 08:27 UTC, merged