Add Opensuse dbus and pam whitelisting checks
rpm-software-management/rpmlint pull request #629
Opened 2021-04-26 13:38 UTC by acipm

Adds dbus services whitelisting and ghost file checks in `DBusServicesCheck`.
Adds check for pam ghost files in `PAMModulesCheck`.

2021-05-04 09:33 UTC, mgerstner commented
looks good to me

2021-05-10 14:44 UTC, marxin requested changes

2021-05-10 14:44 UTC, marxin commented on rpmlint/checks/DBusServicesCheck.py
> +    _dbus_system_paths = [
Please remove the leading `_`.

2021-05-10 14:44 UTC, marxin commented on rpmlint/checks/DBusServicesCheck.py
> +
Remove the extra new line.

2021-05-10 14:44 UTC, marxin commented on rpmlint/descriptions/DBusServicesCheck.toml
> +AUDIT_BUG_URL = "https://en.opensuse.org/openSUSE:Package_security_guidelines#audit_bugs"
Please create a new `rpmlint/descriptions/Variables.toml` file and mode there `AUDIT_BUG_URL` and remove all other definitions of it `git grep 'AUDIT_BUG_URL = '`.

2021-05-10 18:41 UTC, marxin commented
Thank you for the pull request.

2021-05-10 18:41 UTC, merged