WIP: Rewrite parts of FileDigestCheck
rpm-software-management/rpmlint pull request #655
Opened 2021-05-30 23:27 UTC by acipm

file-digest-mismatch is not triggered when a whitelist entry exists but the digest is wrong. This rewrites parts of the FileDIgestCheck to fix the bug.

Please **don't** merge before @mgerstner has reviewed.

2021-06-11 07:59 UTC, marxin commented
Please rebase it.
@mgerstner : Can you please review it?

2021-06-22 07:56 UTC, mgerstner commented on rpmlint/checks/FileDigestCheck.py
> +                    error = False
to make the code a bit more compact you could consider dropping the `error` variable and simply reset `error_digests = []`. Or do you think it hurts readability of the code?

2021-06-22 07:58 UTC, mgerstner commented
Apart from the one idea I commented about the change looks good to me. Also nice that you commented the code to make it more easily understandable, since this logic is non-obvious for people outside of our review team.

2021-06-22 08:51 UTC, mgerstner commented
@acipm: And one more thing: Can you please adjust the unit tests so that this aspect is actually covered in the future?

2021-06-22 10:50 UTC, acipm commented
> @acipm: And one more thing: Can you please adjust the unit tests so that this aspect is actually covered in the future?

done

2021-06-22 11:35 UTC, mgerstner approved these changes
LGTM now.

2021-06-22 12:23 UTC, marxin requested changes
Can you please submit the newly created test-case to `https://build.opensuse.org/project/show/devel:openSUSE:Factory:rpmlint:tests`?

2021-06-22 17:44 UTC, merged