Whitelist /var/spool/mail in postfix, sendmail and exim (bsc#1179574)
rpm-software-management/rpmlint pull request #929
Opened 2022-09-13 08:21 UTC by lnussel

This is just moving a directory from the filesystem package where it already is whitelisted to the actual users of the directory.

2022-09-13 10:58 UTC, marxin requested changes

2022-09-13 10:58 UTC, marxin commented on configs/openSUSE/world-writable-whitelist.toml
> +group = "root"
Please remove this change.

2022-09-13 13:04 UTC, marxin approved these changes

2022-09-13 13:08 UTC, mgerstner commented
If the directory is no longer in the file system package can you then please also remove the old entry?

2022-09-13 14:23 UTC, lnussel commented
it is still there. I can remove it only when the other packages are in

2022-09-14 08:52 UTC, mgerstner commented
Okay, a cleanup PR# once it is possible would be nice. Thanks!

2022-09-14 08:52 UTC, mgerstner approved these changes

2022-09-14 08:53 UTC, merged